version: 0.0
os: linux
files:
  - source: /composer.json
    destination: /usr/share/nginx/html/composer.json
  - source: /composer.phar
    destination: /usr/share/nginx/html/composer.phar
  - source: /composer.lock
    destination: /usr/share/nginx/html/composer.lock
  - source: /oil
    destination: /usr/share/nginx/html/oil
  - source: /fuel
    destination: /usr/share/nginx/html/fuel
  - source: /public
    destination: /usr/share/nginx/html/public
hooks:
  AfterInstall:
    - location: scripts/change_owner.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
